### ISSUE TITLE
[AUG 5WEEK] 구현과 BFS/DFS

### ISSUE THREAD

**Issue by sieunnnn** [seinShin/CodingTestStudy#1]
# 알고리즘
- 구현
- BFS
- DFS

# TODO
### `시은`
- [x] 이론 공부
- [x] 백준 문제 풀이

### `세인`
- [x] 이론 공부
- [x] 백준 문제 풀이

<br>

**Comment by sieunnnn** [comment]
# 백준 1010

<br>

첫번째 시도 코드에서 `시간초과` 로 실패 했습니다. 🥲 
해당 코드 공유합니다.

```
package implementation;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;

public class Aug5Week_1010_Kse {

    public static void main(String[] args) throws IOException {

        /**
         * 서쪽 N 개, 동쪽 M 개
         * N 개만큼 다리를 지을건데, 다리를 지을 수 있는 경우의 수
         * M 개 중 N 개를 뽑는 문제 => 조합
         */

        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringBuilder sb = new StringBuilder();

        int N = Integer.parseInt(br.readLine());

        for (int i = 0; i < N; i++) {
            StringTokenizer st = new StringTokenizer(br.readLine());

            int r = Integer.parseInt(st.nextToken());
            int n = Integer.parseInt(st.nextToken());

            sb.append(combination(n, r)).append("\n");
        }

        System.out.println(sb);
    }

    public static int combination(int n, int r) {
        if (n == r || r == 0) return 1;
        return combination((n - 1), (r - 1)) + combination(n - 1, r);
    }
}
```

**Comment by seinShin** [comment]
# 백준 1010

저는 이 부분 팩토리얼로 접근을 하였는데
세 번 시도하였습니다.

1. `재귀 함수`를 사용한 팩토리얼 함수 -> stackoverflow가 발생하였습니다.
2. `반복문`을 사용한 팩토리얼 함수 -> int형을 사용할 경우 범위가 초과되었습니다.
3. 2번에서 만든 팩토리얼 함수를 사용하되 `double`형으로 자료형을 바꾸어 해결하였습니다.

코드 공유합니다.

```
package implementation;

import java.util.Scanner;
public class Aug5Week_1010_Ssi {

    //팩토리얼 함수 -> 재귀함수로 짤 경우 수가 커지면 stackOverFlow 발생
   /* static int factorial(int n){
        if (n ==1){
            return 1;
        }else{
            return n * factorial(n-1);
        }
    }*/

    //팩토리얼 함수 2 -> 반복문 형태로 수정 / int로 하면 범위 초과 double로 하면 소수점 고려
    static double factorial(double n){
        if (n<=1) return 1;

        double f = 1;
        for(double i=1;i<n+1;i++){
            f *= i;
        }

        return f;
    }
    static double combination(double n, double m){
        double mf = factorial(m);
        double mnf = factorial(m-n);
        double nf = factorial(n);

        return mf/(mnf*nf);
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int t = sc.nextInt();

        for (int i=0; i<t; i++){
            double n = sc.nextInt();
            double m = sc.nextInt();

            System.out.printf("%.0f\n", combination(n,m));
        }
    }
}
```

**Comment by sieunnnn** [comment]
# 백준 1010
<br>

저는 다른방식으로 해결해보았습니다! 손으로 그려보는데, 반복되고 불필요한 연산이 나타나더군요!
제한 시간이 0.5 초라 이런 연산을 줄이면 원래 사용하던 조합 메서드를 사용할 수 있을것 같았습니다.
해당 코드 공유합니다!
<br>

```
package implementation;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;

public class Aug5Week_1010_Kse {

    // 다리의 최대 개수가 30 개로 지정되어 있다.
    private static final int[][] dp = new int[31][31];

    public static void main(String[] args) throws IOException {

        /**
         * 서쪽 N 개, 동쪽 M 개
         * N 개만큼 다리를 지을건데, 다리를 지을 수 있는 경우의 수
         * M 개 중 N 개를 뽑는 문제 => 조합
         * 0 < N, M < 30
         *
         * 손으로 쓰면서 확인해보니 불필요한 연산이 중복되는 것을 알았습니다.
         * 테스트 케이스 1, 2 의 경우 수가 작아 depth 가 작지만, 수가 커질경우 문제가 생길 것 같습니다.
         * 따라서 아래와같이 이미 수행하거나 수행할 필요가 없는 연산은 제거하도록 코드를 변경하였습니다.
         */

        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringBuilder sb = new StringBuilder();

        int N = Integer.parseInt(br.readLine());

        for (int i = 0; i < N; i++) {
            StringTokenizer st = new StringTokenizer(br.readLine());

            int r = Integer.parseInt(st.nextToken());
            int n = Integer.parseInt(st.nextToken());

            sb.append(combination(n, r)).append("\n");
        }

        System.out.println(sb);
    }

    public static int combination(int n, int r) {

        if (dp[n][r] > 0) {
            return dp[n][r];

        } else if (n == r || r == 0) {
            return dp[n][r] =  1;

        } else {
            return dp[n][r] = combination((n - 1), (r - 1)) + combination(n - 1, r);
        }
    }
}
```

**Comment by sieunnnn** [comment]
# 다시 생각해보기 
- 백준 1010 문제 DP 배우고 다시 접근해보기 (Memoization)

<br>

# 1010 피드백 
- StackOverflow == 재귀가 계속 돈다.
- `double` 오차범위가 기재되어 있거나 `Long` 을 사용했는데도 범위가 초과하는 경우에 사용합니다!
- 만약 `Long` 을 사용했는데도 범위 초과가 난다면 로직을 수정해야 합니다.
- `BigInteger` 는 성능이 좋지 않다.

<br>

# 1094 문제의 확장
- 비트연산으로 1의 개수를 구하면 같은 결과가 나옵니다.
- `문제` 1a+2b+4c+8d+16e+32f+64g= k 일때 a ~ g 의 합 (단 , a ~ g 는 0 또는 1) => 막대의 개수 == 해 == k
- 원래 풀었던 대로 푸는것에 비해 시간복잡도는 비슷하지만 공간복잡도는 줄어듭니다.
<br>

**Comment by seinShin** [comment]
# 백준 11403

bfs를 사용하여 풀었는데 답은 나오는데 ArrayIndexOutOfBoundsException이 자꾸 나오네요ㅠㅠ

길이를 넘어간 것 같지 않은데 같이 찾아주세용..@_@

 ***
    package graph_bfs_dfs;
    
    import java.io.*;
    import java.util.*;
    public class Aug5Week_11403_Ssi {
  
      public static ArrayList<Integer>[] graph;
      public static void bfs(int v, boolean[] visited){
        Queue<Integer> q = new LinkedList<>();
        q.add(v);

        while(!q.isEmpty()){
            int node = q.poll();
            
            // 에러 나는 부분
            for(int x : graph[node]){
                if(visited[x] == false){
                    visited[x] = true;
                    q.add(x);
                }
            }
        }

        for(int i=1;i<visited.length;i++){
            if(visited[i] == true){
                System.out.print(1 + " ");
            }else{
                System.out.print(0 + " ");
            }
        }

    }
    public static void main(String[] args) throws IOException {
        BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
        int n = Integer.parseInt(bf.readLine());

        graph = new ArrayList[n+1];

        for(int i=1; i<n+1;i++){
            graph[i] = new ArrayList<Integer>();
        }

        for(int i=0;i<n+1;i++){
            String arr[] = bf.readLine().split(" ");

            for(int j=0;j<arr.length;j++){
                if(Integer.parseInt(arr[j]) == 1) {
                    graph[i + 1].add(j + 1);
                }
            }
        }

        for(int i=0;i<n+1;i++){
            boolean[] visited = new boolean[n+1];
            bfs(i+1, visited);
            System.out.println();
        }
    }
}

***

**Comment by seinShin** [comment]
# 백준 11403 추가내용

- 플로이드 와샬 알고리즘을 사용하여 해결한 풀이법을 공유합니다.
`플로이드 와샬` : 모든 정점에서 다른 모든 정점으로의 최단 경로를 구하는 알고리즘

** 원래는 최단 경로를 구하는 알고리즘이지만 이 문제의 경우 갈 수 있는지 여부만 파악하면 되기 때문에 최솟값을 구하는 과정만 변경하여 주었습니다.

***
     package graph_bfs_dfs;
  
     import java.io.*;
     import java.util.*;
     public class Aug5Week_11403_2_Ssi {
      public static void main(String[] args) throws IOException {
         BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
         int n = Integer.parseInt(bf.readLine());

        //행렬
        int[][] graph = new int[n][n];

        for(int i=0; i<n;i++){
            StringTokenizer st = new StringTokenizer(bf.readLine());
            for(int j=0; j< n; j++){
                graph[i][j] = Integer.parseInt(st.nextToken());
            }
        }

        /***
         *  플로이드 워셜
         k - 거쳐가는 노드, i - 시작 노드, j - 끝 노드
         최단 거리를 구할 경우는 k를 거쳐갈 때와 아닐때의 값을 비교하여 최단거리를 구합니다.
         이 문제에서는 최단거리가 아닌 경로 여부만 판단합니다.
         ***/

        for(int k=0; k<n;k++){
            for(int i=0; i<n;i++){
                for(int j=0; j<n; j++){
                    if(graph[i][k] == 1 && graph[k][j] == 1){
                        graph[i][j] = 1;
                    }
                }
            }
        }


        //출력
        StringBuilder sb = new StringBuilder();
        for(int i=0; i<n;i++){
            for(int j=0; j<n;j++){
                sb.append(graph[i][j] + " ");
            }
            sb.append("\n");
        }
        System.out.println(sb);
    }
}


***

**Comment by sieunnnn** [comment]
# 백준 11403
저는 문제를 읽고 DFS 로 푸는게 적합하다는 생각을 하였습니다.
행을 기준으로 잡고 한 열씩 탐색을 해나갔고, 정답을 도출하게 되었습니다.
코드는 아래와 같습니다.
<br>

```
package graph_bfs_dfs;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class Aug5Week_11403_Kse {

    /**
     * @Variable N : 정점의 개수
     *
     * 인접행렬 형식으로 출력
     * i -> j  간선 존재 = 1
     */

    public static int[][] graph;
    public static int[][] answer;
    public static boolean[] visited;
    public static int N; // 정점의 개수

    public static void dfs (int x, int y) {
        for (int i = 0; i < N; i++) {
            if (graph[y][i] == 1 && !visited[i]) {
                visited[i] = true; // 방문처리
                answer[x][i] = 1; // 경로 존재 처리

                dfs(x, i);
            }
        }

    }

    public static void main (String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringBuilder sb = new StringBuilder();
        N = Integer.parseInt(br.readLine());

        graph = new int[N][N];
        answer = new int[N][N];
        visited = new boolean[N];

        // 그래프 그리기
        for(int i = 0; i < N; i++) {
            String[] temp = br.readLine().split(" ");
            for (int j = 0; j < temp.length; j++) {
                graph[i][j] = Integer.parseInt(temp[j]);
            }
        }

        for (int i = 0; i < graph.length; i++) {
            visited = new boolean[N];
            dfs(i, i);
        }

        // 정답 출력
        for (int i = 0; i < answer.length; i++) {
            for (int j = 0; j < answer.length; j++) {
                sb.append(answer[i][j]).append(" ");
            }
            sb.append("\n");
        }
        System.out.println(sb);
    }
}

```

## 플로이드 와샬 알고리즘
- 최단거리를 구할 때 사용한다고 들었습니다.
- 삼중포문을 사용하기 때문에 조건을 확인해야 하나, 해당 문제에서는 N 이 100 이하이기 때문에 써도 충분할 것 같습니다.
- 저의 경우 아직 배우는 단계라 그래프를 그리고, 손으로 그리는데에 시간을 많이 할애했습니다! 🥹

<br>
