### ISSUE TITLE
[SEP 4WEEK] 9월 4주차 문제 

### ISSUE THREAD

**Issue by seinShin** [seinShin/CodingTestStudy#9]
# 9월 4주차 문제

- 구현 1문제
- 알고리즘 1문제

**Comment by seinShin** [comment]
# 백준 2167-2차원 배열의 합 

테케는 다 통과하는데 뭐가 잘못된걸까요..? 일단 리프레쉬 후 보려고 하는데 같이 고민해주세용ㅠㅠ

```
package implementation;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;

public class Sep4Week_2167_Ssi {
    static int n;
    static int m;
    static int k;
    static int i,j,x,y;
    static int[][] arr;
    static int[][] dp;

    public static void main(String[] args) throws IOException {
        BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
        StringTokenizer st;

        st = new StringTokenizer(bf.readLine());
        n = Integer.parseInt(st.nextToken());
        m = Integer.parseInt(st.nextToken());

        arr = new int[n][m];
        dp = new int[n+1][m+1];

        for(int i=0;i<n; i++){
            st = new StringTokenizer(bf.readLine());
            arr[i][0] = Integer.parseInt(st.nextToken());
            arr[i][1] = Integer.parseInt(st.nextToken());
            arr[i][2] = Integer.parseInt(st.nextToken());
        }


        for(int i=1; i< n+1 ;i++){
            for(int j=1; j< m+1 ;j++){
                dp[i][j] = dp[i][j-1]+dp[i-1][j]-dp[i-1][j-1]+arr[i-1][j-1];
            }
        }


        k = Integer.parseInt(bf.readLine());
        for(int m=0; m< k ;m++){
            st = new StringTokenizer(bf.readLine());

            i = Integer.parseInt(st.nextToken());
            j = Integer.parseInt(st.nextToken());
            x = Integer.parseInt(st.nextToken());
            y = Integer.parseInt(st.nextToken());

            System.out.println(dp[x][y]-dp[x][j-1]-dp[i-1][y]+dp[i-1][j-1]);
        }
    }
}

```

**Comment by sieunnnn** [comment]
> # 백준 2167-2차원 배열의 합
> 테케는 다 통과하는데 뭐가 잘못된걸까요..? 일단 리프레쉬 후 보려고 하는데 같이 고민해주세용ㅠㅠ
> 
> ```
> package implementation;
> 
> import java.io.BufferedReader;
> import java.io.IOException;
> import java.io.InputStreamReader;
> import java.util.StringTokenizer;
> 
> public class Sep4Week_2167_Ssi {
>     static int n;
>     static int m;
>     static int k;
>     static int i,j,x,y;
>     static int[][] arr;
>     static int[][] dp;
> 
>     public static void main(String[] args) throws IOException {
>         BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
>         StringTokenizer st;
> 
>         st = new StringTokenizer(bf.readLine());
>         n = Integer.parseInt(st.nextToken());
>         m = Integer.parseInt(st.nextToken());
> 
>         arr = new int[n][m];
>         dp = new int[n+1][m+1];
> 
>         for(int i=0;i<n; i++){
>             st = new StringTokenizer(bf.readLine());
>             arr[i][0] = Integer.parseInt(st.nextToken());
>             arr[i][1] = Integer.parseInt(st.nextToken());
>             arr[i][2] = Integer.parseInt(st.nextToken());
>         }
> 
> 
>         for(int i=1; i< n+1 ;i++){
>             for(int j=1; j< m+1 ;j++){
>                 dp[i][j] = dp[i][j-1]+dp[i-1][j]-dp[i-1][j-1]+arr[i-1][j-1];
>             }
>         }
> 
> 
>         k = Integer.parseInt(bf.readLine());
>         for(int m=0; m< k ;m++){
>             st = new StringTokenizer(bf.readLine());
> 
>             i = Integer.parseInt(st.nextToken());
>             j = Integer.parseInt(st.nextToken());
>             x = Integer.parseInt(st.nextToken());
>             y = Integer.parseInt(st.nextToken());
> 
>             System.out.println(dp[x][y]-dp[x][j-1]-dp[i-1][y]+dp[i-1][j-1]);
>         }
>     }
> }
> ```

## 반례
```
4 4
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16
3
2 2 3 3
2 4 4 4
3 1 4 4

#정답
34
36
100

#출력 (세인님 코드)
34
0
72
```

점화식이 약간 저랑 다르긴 한데... 디버그 찍어보려다 엄두가 안나서 못찍어봐써여... ㅋㅋㅋㅋㅋ
첫번째 테스트 케이스를 테이블로 표현하면 아래와 같을 거에요.
|||||
|:---:|:---:|:---:|:---:|
||dp[1][1]|dp[1][2]|dp[1][3]|
||dp[2][1]|dp[2][2]|dp[2][3]|

그리고 여기서 누적합을 dp로 구하면,,,
```
dp[1][1] = dp[1][0] + arr[1][1]
dp[1][2] = dp[1][1] + arr[1][2]
...
dp[2][3] = dp[2][2] + arr[2][3]
```
이렇게 될겁니다요.

그리고 저는 행을 기준으로 계산을 했답니다.
첫번째 테스트 케이스는 (1, 1) (2, 3) 이고, 행을 기준으로 계산 할거기 때문에 i ~ x 까지 for문을 돌릴거에요.
그리고 아래와 같이 더할겁니당

sums[k] += dp[row][y] - dp[row][j  - 1];

풀어서쓰면,
첫번째 for 문: dp[1][3] - dp[1][0];
** dp[1][0] = 0;
두번째 for 문: dp[2][3] - dp[2][0];
** dp[2][0] = 0;

세번째 테스트 케이스의 경우 (1, 3) (2, 3) 입니다.
첫번째 for 문: dp[1][3] - dp[1][2] = (dp[1][2] + arr[1][3]) - dp[1][2]
두번째 for 문: dp[2][3] - dp[2][0];
** dp[2][0] = 0;

점화식에서 문제가 있는것 같은데, 제 풀이가 해결하는데 도움이 되었으면 좋겠네용!
